name: Build
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        name: Checkout repository

      - name: Install poetry
        run: pipx install poetry
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
          
      - name: Update pip and install Pylint and flake8
        run: |
            python3 -m pip install --upgrade pip
            python3 -m pip install pylint flake8 flake8-sarif-formatter
          
      - name: Build with Poetry
        run: poetry install --no-interaction --no-ansi

      - name: Run pylint
        run: poetry run pylint -j 0 ./adcheck --ignore-paths=^adcheck/libs --exit-zero

      - name: Run flake8
        run: python3 -m flake8 --exclude=libs --format=sarif --output-file=results.sarif

      - name: Upload flake8 scan SARIF report
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@0499de31b99561a6d14a36a5f662c2a54f91beee
        with:
          sarif_file: results.sarif
